---

# Install Vundle
- name: Make Vim directory
  file: path={{ vundle_vim_dir }} owner={{ vundle_user }} group={{ vundle_group }} mode=0755 state=directory
- name: Make Vim bundle directory
  file: path={{ vundle_vim_dir }}/bundle owner={{ vundle_user }} group={{ vundle_group }} mode=0755 state=directory
- name: Clone vundle
  git: repo={{ vundle_repo }} dest={{ vundle_vim_dir }}/bundle/Vundle.vim update=no
  become: true
  become_user: "{{ vundle_user }}"
  register: vundle_installed

# Install Vim plugins
- name: Install Vim plugins
  command: su - {{ vundle_user }} -c "vim -E -s -c 'source ~/.vimrc' -c PluginInstall -c qall"
  register: vim_plugins_installed
  changed_when: vim_plugins_installed.rc != 0
  when: vundle_installed is changed
